export default defineEventHandler(async (event) => {
    const DUMMY_DATA = [
        {
            id: '14401',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '美食探店驚喜包',
            area: '',
            name: '【美食探店驚喜包】多家神秘知名餐廳，等著各路吃貨來嚐鮮',
            description: '',
            image: 'https://images.unsplash.com/photo-1575932444877-5106bee2a599?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://google.com',
            price: '9999',
            note1: '',
            note2: '',
            try_content:
                '專業的吃貨就是只要提到美食絕對不落人後！<br />\r\n這次美食探店驚喜包！集結多家知名好評餐廳<br />\r\n無論你是喜歡鐵板燒、日式料理、燒肉店～<br />\r\n只要報名就有機會到店內享用美味餐點！<br />\r\n報名資格很簡單，詳見下方<br />\r\n<br />\r\n● 報名資格：有經營 部落格、FB、IG、TikTok、Youtube任一社群平台者。<br />\r\n● 報名方式：點選上方【立即參加】回答問題，並留下正確資料，後續與品牌廠商媒合後，會以信件提供合作機會！（將依所在地區及合適度分發）<br />\r\n● 稿酬：請於表單內填寫，報價將會影響後續篩選資格，再請謹慎填寫！<br />\r\n<br />\r\n趕緊報名體驗就有機會免費體驗美味佳餚唷！<br />\r\n美食探店驚喜包將依所在地區及合適度分發！<br />\r\n<br />\r\n◎活動說明<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得您所在地區附近的餐廳體驗。<br />\r\n2.發表體驗心得：錄取者到店體驗後，需在14天內發表一篇部落格文章or社群貼文or短影音or長片（依屆時探店活動任務而定），並依照信件指示回覆稿件連結。（時間依屆時錄取信件通知為準）<br />\r\n3.稿件規範：<br />\r\n(1) 部落格文章字數需800字以上及10張(含以上) 的體驗情境照片，包含至少２張產品獨照，須包含個人體驗心得。<br />\r\n(2) 社群貼文字數需100字及5張(含以上) 的體驗情境照片。<br />\r\n(3) 短影音約莫30~60秒，有人聲口白+字幕尤佳。<br />\r\n(4) YT長片約莫8分鐘，有人聲口白+字幕尤佳。<br />\r\n4.Lonely Travel與(餐廳)將擁有該稿件(影音、文字、圖片)之擁有使用及審核修改權。<br />\r\n5.參與本次體驗活動所產出的心得文章，意即同意授權給(餐廳)行銷宣傳使用，使用範圍包含官方網站、購物平台、活動網頁或其他管道通路作為產品推廣之用。',
            try_notice:
                '＊注意事項<br />\r\n1.報名時請務必填寫正確資訊，如因填寫個人資訊錯誤無法聯繫，即自動喪失資格。<br />\r\n2.報名前請務必確認活動規範，若未完成上述事項，未來將影響您參與【旅行家鐵人賽】活動之權益，敬請留意。<br />\r\n3.Lonely Travel保有最終修改、變更、活動解釋及取消本活動之權利，若有相關異動將會公告於網站，恕不另行通知。<br />\r\n4.本活動產品之寄送地址僅限台灣地區。<br />\r\n5.參與本次體驗活動所產出的心得文章，意即同意授權給該品牌行銷宣傳使用，使用範圍包含官方網站、購物平台、活動網頁或其他管道通路作為產品推廣之用。',
            try_count: '9999',
            start_at: '2024-10-25 19:00:00',
            end_at: '2026-10-14 00:00:00',
            show_at: '2024-10-14 17:00:00',
            hide_at: '2025-10-14 00:00:00',
            status: '1',
            try_join_count: 296,
            try_join_pass_count: '0',
            try_questionnaire_id: 2836,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '0',
            tag_id: '0',
            online_article_count: '0',
            try_end_url: '',
            memo1: '',
            memo2: '',
            memo3: '',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '14485',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '酒條通洋酒',
            area: '',
            name: '浪游歐美的私廚女王 探索美酒與美饌的極致搭配 x 酒條通VIP會員專屬體驗',
            description: '',
            image: 'https://images.unsplash.com/photo-1643717582997-45650849f0c2?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.609.com.tw/',
            price: '2500/含酒搭餐',
            note1: '1份',
            note2: '',
            try_content:
                '酒條通一直以來為大家搜羅與嚴選各地優質的紅白酒，此次全新升級，將品酒文化帶入更高層次！未來，酒條通將為VIP貴賓打造專屬『私廚料理品酒活動』，結合頂級佳餚與精選美酒，呈現獨一無二的私廚品酒享受。<br />\r\n<br />\r\n本次活動與聯名，將首度揭開這項服務的序幕，邀請您一同體驗量身定制的品酒時光。<br />\r\n<br />\r\n＃主廚簡介：<br />\r\n浪游歐美的私廚女王 「華澐恩」 祖父母來自江蘇無錫，自小便在家族的傳統江浙菜香中成長，深得江南風味的精髓。熱愛西餐與烘焙，並融合多年旅居歐美的經歷，以匠心創作符合本地風味的西式料理與點心。 主廚專注於客製化到宅廚藝服務，精心規劃中西式主題餐宴，亦曾於高端私人會所中打造獨特的饗宴體驗，以料理為詩，為食客們譜寫一段段優雅的故事。<br />\r\n<br />\r\n＃體驗時間：12/19 中午12點<br />\r\n＃體驗地點：台北市中山區民生東路一段30號B1<br />\r\n（坐捷運的話「雙連站1出口」，公車是「華泰飯店站」）<br />\r\n＃餐酒：四款葡萄酒（敬請期待）<br />\r\n<br />\r\n＃VIP菜色：<br />\r\n1.冷盤(牛豬雙寶、手拍翠玉黃瓜、松柏長青)<br />\r\n2.霸王雞<br />\r\n3.滬上炒飯<br />\r\n4.果律松子蝦球<br />\r\n5.本幫金磚封肉<br />\r\n6.鮮蝦腐皮捲佐冰梅醬<br />\r\n7.香芹雙鮮<br />\r\n8.蔭瓜鮮蒸鰉魚<br />\r\n9.蓮花雞湯<br />\r\n10.冰糖雪花梨<br />\r\n11.寶島果盤<br />\r\n<br />\r\n參考更多：如底部連結<br />\r\n<br />\r\n＊活動說明<br />\r\n◎本次活動價值$2500，邀請獲選美食部落客免費體驗<br />\r\n◎報名資格：限Lonely Travel註冊會員。<br />\r\n◎報名方式：點選立即參加按鈕並留下正確資料。<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得體驗資格。<br />\r\n2.試用並發表體驗心得：錄取者體驗完成後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約10天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n(1)文章字數800字以上，須包含個人體驗心得並分享至FB或IG。<br />\r\n(2)圖片10張以上，可為：店家裝潢、Logo、產品圖片、體驗情境照、與產品合照等。',
            try_notice: '',
            try_count: '16',
            start_at: '2024-12-19 11:00:00',
            end_at: '2025-10-14 00:00:00',
            show_at: '2024-12-06 18:00:00',
            hide_at: '2025-10-14 00:00:00',
            status: '1',
            try_join_count: 40,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '5',
            tag_id: '6286',
            online_article_count: '3',
            try_end_url: '',
            memo1: '美酒美饌',
            memo2: '800字',
            memo3: '10張照片',
            memo4: '分享FB/IG',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '13861',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '合豐鼎實業',
            area: ' ',
            name: '凱度極品花香咖啡',
            description: '',
            image: 'https://images.unsplash.com/photo-1522850959516-58f958dde2c1?q=80&w=1605&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.pixgo.com.tw/ezpretty/shop/good/7623?ed=6a9c693f387b6faa9a5d0bfe42341744',
            price: '350',
            note1: '玫瑰花香咖啡＊2包＋桂花花香咖啡＊3包/盒',
            note2: 'https://docs.google.com/document/d/1Fi2zZEhLpG4C2VPza2Jwl5qEQdJUNP0M/edit?usp=drive_link&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '品名：凱度極品花香咖啡<br />\r\n玫瑰花香咖啡＊2包＋桂花花香咖啡＊3包<br />\r\n内容物：天然新鮮花瓣+配方豆研磨式咖啡 咖啡豆產地：中南美洲100%Arabica<br />\r\n成分：100%純研磨式咖啡粉<br />\r\n淨重：10公克士 0.5g<br />\r\n保存期限：18個月<br />\r\n🔘風味甘甜平衡醇厚卻柔順，豐富的花香與堅果香氣<br />\r\n🔘特別用天然花瓣製作可以更平衡咖啡的風味，讓口感溫和，製作好的花香咖啡整體的口感將更為圓潤<br />\r\n🔘前段花香香氣，中段平衡果香，尾段濃郁咖啡尾韻<br />\r\n🟨凱度咖啡嚴選百分之百阿拉比卡咖啡豆調配出的經典義式風味的咖啡，在用最佳比例的天然花瓣系列桂花、玫瑰兩系列的花瓣咖啡，淡淡的花香讓咖啡增加不少風味，值得您細細品嚐<br />\r\n<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n(1)文章字數500字，請以口感、滿足幸福感、產品品質及包裝質感為主撰文。<br />\r\n(2)圖片6張以上照片產品獨照、與產品合照、使用情境、商品特寫近照，如能拍短影片更好。',
            try_notice: '',
            try_count: '25',
            start_at: '2024-09-21 00:00:00',
            end_at: '2024-10-13 23:59:00',
            show_at: '2024-08-23 08:00:00',
            hide_at: '2025-10-14 00:00:00',
            status: '1',
            try_join_count: 119,
            try_join_pass_count: '25',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '21',
            tag_id: '5938',
            online_article_count: '20',
            try_end_url: '',
            memo1: '',
            memo2: '500字以上',
            memo3: '6張以上',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1522850959516-58f958dde2c1?q=80&w=1605&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '1',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1574174914167-a97ce4905434?q=80&w=1962&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '1',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1707905644807-1d20b965c580?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '1',
                },
            ],
            videos: [],
        },
        {
            id: '14440',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '健司',
            area: '',
            name: '炭燒魅力，風味昇華【三上食樂-極上壽喜炭燒 牛肉/豚肉】職人手工熬製，承襲日本醬汁靈魂！',
            description: '',
            image: 'https://images.unsplash.com/photo-1677029969065-c9f4003a9ad5?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.mayumi.com.tw/',
            price: '嫩牛109元+豚肉109元',
            note1: '1份',
            note2: 'https://1px.tw/RZB6xtuM',
            try_content:
                '新品上市！【三上食樂 極上壽喜炭燒 牛肉/豚肉 120g】<br />\r\n1.日式正宗風味，承襲日本醬汁靈魂。<br />\r\n2.職人手工熬製，72小時熟成，湯頭濃郁而圓潤，滋味十足。<br />\r\n3.醬汁厚實，濃郁精華。(配整碗飯很剛好，或是做成小小的壽喜燒鍋也OK。如果打一顆散蛋變成親子丼飯。)<br />\r\n4.炭燒魅力，風味升華，層次分明！(炭燒風味市面上沒有。)<br />\r\n5.多種創意料理運用。(例如只要加一顆溫泉蛋就變成丼飯，壽喜燒吐司夾蛋等等)<br />\r\n6.立袋有兩邊可以撕的孔，微波時開一邊的孔，加熱後再開另一邊的孔比較不會燙傷，設計很貼心。<br />\r\n7.簡單微波爐非常的方便。(開一小孔即可，不要開太大孔。)<br />\r\n＊目前僅在全聯實體通路販售<br />\r\n<br />\r\n＊活動說明<br />\r\n◎報名資格：限Lonely Travel註冊會員。<br />\r\n◎報名方式：點選立即參加按鈕並留下正確資料。<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，Lonely Travel將提供錄取者全聯禮券300元，須自行購買商品（每人至少需購買兩種口味各一盒）。<br />\r\n2.試用並發表體驗心得：錄取者收到產品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約12天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n(1)文章字數500字以上，須包含個人體驗心得。<br />\r\n(2)圖片5張以上，可為：產品完整包裝、Logo、產品圖片、體驗情境照、與產品合照。',
            try_notice: '',
            try_count: '30',
            start_at: '2024-11-05 00:00:00',
            end_at: '2023-11-17 23:59:00',
            show_at: '2024-10-23 00:00:00',
            hide_at: '2025-10-14 00:00:00',
            status: '1',
            try_join_count: 119,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '31',
            tag_id: '6214',
            online_article_count: '30',
            try_end_url: '',
            memo1: '日式正宗風味',
            memo2: '500字以上',
            memo3: '5張照片',
            memo4: '提供禮券購買',
            label_image_url: '',
            show_trial_exp: '1',
            rate: {
                rate1: {
                    name: '正宗口味',
                    avg: 8.74,
                },
                rate2: {
                    name: '醬汁濃郁',
                    avg: 8.84,
                },
                rate3: {
                    name: '料理方便',
                    avg: 9.52,
                },
                rate4: {
                    name: '回購意願',
                    avg: 8.23,
                },
                rate5: {
                    name: '總評分',
                    avg: 8.58,
                },
            },
            tryget: '這次開箱三上食楽的極上壽喜炭燒牛/豚肉料理包，我覺得比較特別的是加了炭燒的香氣，醬汁也夠濃。 搭配飯麵都很適合，如果要做小火鍋因為有加水，建議還是要再添加調味~ 這兩款冷凍食品目前僅在全聯販售，喜歡壽喜燒的朋友，可以去試試吧～',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1677029969065-c9f4003a9ad5?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1708388463491-a18979f92116?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1708388463491-a18979f92116?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '1',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1708388463491-a18979f92116?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '1',
                }
            ],
            videos: [
                {
                    title: '【三上食樂-極上壽喜炭燒嫩牛/豚肉】炭燒魅力，風味昇華，職人手工熬製，承襲日本醬汁靈魂！',
                    src: 'https://images.unsplash.com/photo-1590189599125-67138c6509ef?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: 'https://www.youtube.com/shorts/8BCg_MP79ZM',
                    embed: {
                        title: '【三上食樂-極上壽喜炭燒嫩牛/豚肉】炭燒魅力，風味昇華，職人手工熬製，承襲日本醬汁靈魂！',
                        author_name: 'Lonely Travel',
                        author_url: 'https://www.youtube.com/',
                        type: 'video',
                        height: 200,
                        width: 113,
                        version: '1.0',
                        provider_name: 'YouTube',
                        provider_url: 'https://www.youtube.com/',
                        thumbnail_height: 360,
                        thumbnail_width: 480,
                        thumbnail_url:
                            'https://i.ytimg.com/vi/8BCg_MP79ZM/hq2.jpg',
                        html: '<iframe width="200" height="150" src="https://www.youtube.com/embed/8BCg_MP79ZM?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen title="【三上食樂-極上壽喜炭燒嫩牛/豚肉】炭燒魅力，風味昇華，職人手工熬製，承襲日本醬汁靈魂！"></iframe>',
                    },
                    in_title: '1',
                    in_content: '1',
                },
            ],
        },
        {
            id: '14452',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '健司',
            area: '',
            name: '最簡單的滋味，帶給你最純粹的美味【健司-極上酵母餅乾】好吃無負擔！',
            description: '',
            image: 'https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.costco.com.tw/Food-Dining/Snacks/Cookies-Chips/Kenji-Saltine-Crackers-20-g-X-60-Piece/p/209293',
            price: '349',
            note1: '',
            note2: 'https://docs.google.com/document/d/1IKrUsNEwRU25amELVfoJ2IBDIehpdsmd-vrYjLbyV8o/edit?usp=sharing',
            try_content:
                '➤無添加人工甜味劑、色素、香料<br />\r\n➤只用5種原料，小麥粉、油、酵母、芝麻、鹽，成分超單純，美味無負擔<br />\r\n➤使用法國酵母烘焙，口感酥脆不油膩<br />\r\n➤餅體堅持0.2cm厚度~黃金比例 適口性最佳<br />\r\n<br />\r\n＊活動說明<br />\r\n◎報名資格：限Lonely Travel註冊會員。<br />\r\n◎報名方式：點選立即參加按鈕並留下正確資料。<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得產品。<br />\r\n2.試用並發表體驗心得：錄取者收到產品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n(1)文章字數300字以上，須包含個人體驗心得。<br />\r\n(2)圖片5張以上，可為：產品完整包裝、Logo、產品圖片、體驗情境照、與產品合照。',
            try_notice: '',
            try_count: '30',
            start_at: '2024-11-10 17:00:00',
            end_at: '2024-11-30 23:59:00',
            show_at: '2024-10-31 10:00:00',
            hide_at: '2025-10-14 00:00:00',
            status: '1',
            try_join_count: 163,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '29',
            tag_id: '6217',
            online_article_count: '29',
            try_end_url: '',
            memo1: '',
            memo2: '',
            memo3: '',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '1',
            rate: {
                rate1: {
                    name: '低卡健康（10為最高，1為最低）',
                    avg: 8.93,
                },
                rate2: {
                    name: '美味好吃（10為最高，1為最低）',
                    avg: 9.1,
                },
                rate3: {
                    name: '方便攜帶（10為最高，1為最低）',
                    avg: 9.48,
                },
                rate4: {
                    name: '回購率高（10為最高，1為最低）',
                    avg: 9.14,
                },
                rate5: {
                    name: '總評分',
                    avg: 9.14,
                },
            },
            tryget: '健司又出新品啦～極上酵母餅乾，使用法國酵母烘焙，吃起來有淡淡的麥香，口感酥脆不油膩！而且成分單純，只用五種原料做成，吃得安心又放心！更重要的是一包只有95卡，低卡無負擔！下午解饞的好朋友就交給他了～趕快去好事多囤貨吧！',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '結案',
                    src: 'https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '1',
                },
                {
                    title: '宣傳',
                    src: 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?q=80&w=1975&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '1',
                },
            ],
            videos: [
                {
                    title: '健司極上酵母餅乾',
                    src: 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?q=80&w=1975&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: 'https://youtube.com/shorts/i7o2xgs5Wk0?feature=share',
                    embed: {
                        title: '健司極上酵母餅乾',
                        author_name: 'Lonely Travel',
                        author_url: 'https://www.youtube.com/',
                        type: 'video',
                        height: 200,
                        width: 113,
                        version: '1.0',
                        provider_name: 'YouTube',
                        provider_url: 'https://www.youtube.com/',
                        thumbnail_height: 360,
                        thumbnail_width: 480,
                        thumbnail_url:
                            'https://i.ytimg.com/vi/i7o2xgs5Wk0/hq2.jpg',
                        html: '<iframe width="200" height="150" src="https://www.youtube.com/embed/i7o2xgs5Wk0?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen title="健司極上酵母餅乾"></iframe>',
                    },
                    in_title: '1',
                    in_content: '1',
                },
            ],
        },
        {
            id: '14455',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '健司',
            area: '',
            name: '濃郁奶香，甜而不膩【健司 帕蒂小蛋糕】下午茶、點心時間的最佳選擇！',
            description: '',
            image: 'https://images.unsplash.com/photo-1637693902851-6a6a83a09f62?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.costco.com.tw/Food-Dining/Groceries/Baking-Dried-Goods/Kenji-Mini-Party-Cake-15-Count-X-3-Pack/p/147124',
            price: '356',
            note1: '15入x3袋',
            note2: 'https://1px.tw/HK0pivz8',
            try_content:
                '*日本原裝進口<br />\r\n*使用北海道牛奶製作，濃郁奶香，甜而不膩<br />\r\n*日本國產每日新鮮雞蛋製作<br />\r\n*不添加防腐劑，開封後請冷藏保存，三天內食用完畢<br />\r\n*簡單裝飾就可以當作派對小食<br />\r\n* 早餐、下午茶、點心時間最佳選擇<br />\r\n<br />\r\n＊活動說明<br />\r\n◎報名資格：限Lonely Travel註冊會員。<br />\r\n◎報名方式：點選立即參加按鈕並留下正確資料。<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得產品。<br />\r\n2.試用並發表體驗心得：錄取者收到產品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約10天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n(1)文章字數300字以上，須包含個人體驗心得。<br />\r\n(2)圖片5張以上，可為：產品完整包裝、Logo、產品圖片、體驗情境照、與產品合照。',
            try_notice: '',
            try_count: '30',
            start_at: '2024-11-15 00:00:00',
            end_at: '2023-11-24 23:59:00',
            show_at: '2024-10-31 00:00:00',
            hide_at: '2024-11-10 00:00:00',
            status: '0',
            try_join_count: 196,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '29',
            tag_id: '6211',
            online_article_count: '29',
            try_end_url: '',
            memo1: '下午茶可口點心',
            memo2: '300字以上',
            memo3: '5張照片',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '1',
            rate: {
                rate1: {
                    name: '口感綿密',
                    avg: 9.03,
                },
                rate2: {
                    name: '濃郁奶香',
                    avg: 8.9,
                },
                rate3: {
                    name: '派對點心',
                    avg: 9.21,
                },
                rate4: {
                    name: '回購意願',
                    avg: 8.79,
                },
                rate5: {
                    name: '總評分',
                    avg: 9,
                },
            },
            tryget: '我自己是很喜歡健司-帕蒂小蛋糕的用料，日本北海道牛奶融合新鮮雞蛋製作而成，才開袋就能聞到濃郁奶香感，吃起來又甜而不膩，重點是日本原裝進口的，品質讓人放心，一口小蛋糕的大小，份量剛剛好，還在煩惱小孩下午點心吃什麼嗎，健司-帕蒂小蛋糕會是不錯的早餐與下午茶推薦！',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1637693902851-6a6a83a09f62?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1732008209481-3f5eed6b4ab5?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
            ],
            videos: [
                {
                    title: '【健司-帕蒂小蛋糕】濃郁奶香，甜而不膩，下午茶、點心時間的最佳選擇！',
                    src: 'https://images.unsplash.com/photo-1732008209481-3f5eed6b4ab5?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: 'https://www.youtube.com/shorts/MkPWBdOCoSw',
                    embed: {
                        title: '【健司-帕蒂小蛋糕】濃郁奶香，甜而不膩，下午茶、點心時間的最佳選擇！',
                        author_name: 'Lonely Travel',
                        author_url: 'https://www.youtube.com/',
                        type: 'video',
                        height: 200,
                        width: 113,
                        version: '1.0',
                        provider_name: 'YouTube',
                        provider_url: 'https://www.youtube.com/',
                        thumbnail_height: 360,
                        thumbnail_width: 480,
                        thumbnail_url:
                            'https://i.ytimg.com/vi/MkPWBdOCoSw/hq2.jpg',
                        html: '<iframe width="200" height="150" src="https://www.youtube.com/embed/MkPWBdOCoSw?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen title="【健司-帕蒂小蛋糕】濃郁奶香，甜而不膩，下午茶、點心時間的最佳選擇！"></iframe>',
                    },
                    in_title: '1',
                    in_content: '1',
                },
            ],
        },
        {
            id: '14404',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '卡卡食品工業有限公司',
            area: '',
            name: 'KAKA CHEF COLLECTION 大三鮮えびせん 海鮮脆餅(漁場經典原味)',
            description: '',
            image: 'https://images.unsplash.com/photo-1709433420422-731e1be1c9aa?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.ka-ka.com.tw/products/%E6%BC%81%E5%A0%B4%E7%B6%93%E5%85%B8%E5%8E%9F%E5%91%B3',
            price: '100',
            note1: '81G/包',
            note2: '',
            try_content:
                '借鑑日本職人精神,謹守嚴格八道工序,直火慢烤前手工反覆涮染秘制鮮甜蝦醬,鍛造出鹹甜馥郁、濃韻薄脆的海鮮脆餅。<br />\r\n蒜香經典，蒜頭濃郁的醇厚辛香嗆甜滋味，再淋上鮮甜蝦醬的海鮮脆餅，形成令人垂涎的完美搭配。<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】500 字以上，6張以上照片，清楚拍到產品、品牌，撰文請以食用口感、體驗後感受、產品品質及包裝質感為主<br />\r\n【拍攝重點】6張以上照片，清楚拍到產品、品牌',
            try_notice: '',
            try_count: '30',
            start_at: '2024-11-06 12:00:00',
            end_at: '2024-12-07 23:59:00',
            show_at: '2024-10-18 12:00:00',
            hide_at: '2024-11-01 12:00:00',
            status: '0',
            try_join_count: 131,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '29',
            tag_id: '6157',
            online_article_count: '29',
            try_end_url: '',
            memo1: '',
            memo2: '',
            memo3: '',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1709433420422-731e1be1c9aa?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1709433420510-1d3d65d7ac68?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1709433420510-1d3d65d7ac68?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                }
            ],
            videos: [],
        },
        {
            id: '14407',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '卡卡食品工業有限公司',
            area: '',
            name: 'KAKA CHEF COLLECTION 大三鮮えびせん 海鮮脆餅(白川檸檬海鹽)',
            description: '',
            image: 'https://images.unsplash.com/photo-1523568129082-a8d6c095638e?q=80&w=1988&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.ka-ka.com.tw/products/%E7%99%BD%E5%B7%9D%E6%AA%B8%E6%AA%AC%E6%B5%B7%E9%B9%BD',
            price: '100',
            note1: '81G/包',
            note2: '',
            try_content:
                '借鑑日本職人精神,謹守嚴格八道工序,直火慢烤前手工反覆涮染秘制鮮甜蝦醬,鍛造出鹹甜馥郁、濃韻薄脆的海鮮脆餅。<br />\r\n白川檸檬海鹽，爽朗的檸檬清香，和口感「甘醇的海鹽，搭配白胡椒內斂的溫和微辛」，襯托出炭烤海洋食材的旨味。<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】500 字以上，6張以上照片，清楚拍到產品、品牌，撰文請以食用口感、體驗後感受、產品品質及包裝質感為主<br />\r\n【拍攝重點】6張以上照片，清楚拍到產品、品牌',
            try_notice: '',
            try_count: '30',
            start_at: '2024-11-06 12:00:00',
            end_at: '2024-12-07 23:59:00',
            show_at: '2024-10-18 12:00:00',
            hide_at: '2024-11-01 12:00:00',
            status: '0',
            try_join_count: 124,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '28',
            tag_id: '6154',
            online_article_count: '27',
            try_end_url: '',
            memo1: '',
            memo2: '',
            memo3: '',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1523568129082-a8d6c095638e?q=80&w=1988&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1560703649-e3055f28bcf8?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                }
            ],
            videos: [],
        },
        {
            id: '13966',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '健司',
            area: '',
            name: '下午茶時刻就來體驗歐洲起司【健司-金黃起司餅乾】45包大份量高CP值！',
            description: '',
            image: 'https://images.unsplash.com/photo-1541264161754-445bbdd7de52?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.costco.com.tw/Food-Dining/Snacks/Cookies-Chips/Kenji-Golden-Cheese-Crackers-285-g-X-45-Pack/p/81989',
            price: '359',
            note1: '1盒/45包',
            note2: 'https://docs.google.com/document/d/1Aj09supIxInY7DIVub5HeJFz_Lo-Q6Fej5tFiMLdUpI/edit?usp=sharing',
            try_content:
                '＊產品介紹<br />\r\n★使用歐洲進口天然酵母發酵<br />\r\n感受純正歐洲的烘焙口感。<br />\r\n★採用荷蘭進口天然起司<br />\r\n彷彿置身在歐洲荷蘭，濃厚但不膩口的乳酪香撲鼻而來。<br />\r\n★成分天然簡單，無添加任何化學物<br />\r\n食材天然，用最簡單的食材給你最豐富的滋味。<br />\r\n★份量十足，點心首選<br />\r\n外出好攜帶，一包含有5片，簡單包裝迅速成為充飢用最佳夥伴。<br />\r\n（試用產品有效日期：2025/1.2月份）<br />\r\n<br />\r\n＊活動說明<br />\r\n◎報名資格：擁有Lonely Travel部落格的會員。<br />\r\n◎報名方式：請回答問題，留下正確資料就有機會獲得產品並參與此次活動。<br />\r\n<br />\r\n◎活動流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份產品。<br />\r\n2.閱讀並發表體驗心得：錄取者收到產品後，需在14天內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範：<br />\r\n(1)字數300字以上，須包含個人讀後心得。<br />\r\n(2)圖片5張以上，可為：產品完整包裝、產品圖片、體驗情境照、與產品合照',
            try_notice: '',
            try_count: '30',
            start_at: '2024-09-10 00:00:00',
            end_at: '2024-09-26 23:59:00',
            show_at: '2024-09-10 00:00:00',
            hide_at: '2024-09-22 23:59:00',
            status: '0',
            try_join_count: 234,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '31',
            tag_id: '6142',
            online_article_count: '30',
            try_end_url: '',
            memo1: '',
            memo2: '',
            memo3: '',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '1',
            rate: {
                rate1: {
                    name: '好吃涮嘴',
                    avg: 9,
                },
                rate2: {
                    name: '起司濃厚',
                    avg: 9,
                },
                rate3: {
                    name: '飽足感',
                    avg: 10,
                },
                rate4: {
                    name: '回購率高',
                    avg: 9,
                },
                rate5: {
                    name: '總評分',
                    avg: 9,
                },
            },
            tryget: '濃郁起司香，配上天然酵母，簡單調味，輕鬆沒負擔的下午茶搭配，一大盒內有滿滿45包餅乾大份量 CP值超高！',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1541264161754-445bbdd7de52?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1459455356093-6495cff2a2c4?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
            ],
            videos: [
                {
                    title: '【健司-金黃起司餅乾】 下午茶時刻就來體驗歐洲起司！',
                    src: 'https://images.unsplash.com/photo-1459455356093-6495cff2a2c4?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: 'https://youtube.com/shorts/naqZ0r_IZLw?feature=share',
                    embed: {
                        title: '【健司-金黃起司餅乾】 下午茶時刻就來體驗歐洲起司！',
                        author_name: 'Lonely Travel',
                        author_url: 'https://www.youtube.com/',
                        type: 'video',
                        height: 200,
                        width: 113,
                        version: '1.0',
                        provider_name: 'YouTube',
                        provider_url: 'https://www.youtube.com/',
                        thumbnail_height: 360,
                        thumbnail_width: 480,
                        thumbnail_url:
                            'https://i.ytimg.com/vi/naqZ0r_IZLw/hq2.jpg',
                        html: '<iframe width="200" height="150" src="https://www.youtube.com/embed/naqZ0r_IZLw?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen title="【健司-金黃起司餅乾】 下午茶時刻就來體驗歐洲起司！"></iframe>',
                    },
                    in_title: '1',
                    in_content: '0',
                },
            ],
        },
        {
            id: '13975',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '健司',
            area: '',
            name: '【健司-奶油胚芽餅乾】採用歐洲天然酵母 真材實料的好滋味！',
            description: '',
            image: 'https://images.unsplash.com/photo-1524396309943-e03f5249f002?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.costco.com.tw/Food-Dining/Snacks/Cookies-Chips/Kenji-Butter-Crackers-285-g-X-45-Pack/p/81990',
            price: '309',
            note1: '1盒45包',
            note2: 'https://1px.tw/jn0MUiWo',
            try_content:
                '＊產品介紹<br />\r\n￭使用歐洲進口天然酵母發酵<br />\r\n感受純正歐洲的烘焙口感。<br />\r\n￭採用天然奶油所製成之胚芽<br />\r\n含量高達12%美國進口小麥之植物胚芽製作。<br />\r\n￭無添加任何化學物<br />\r\n￭添加美國進口小麥<br />\r\n小包裝好攜帶  一盒45包獨立包裝   一小包含五片<br />\r\n一口咬下淡淡的鹹香及奶油的香氣 給你最純粹的滋味～<br />\r\n<br />\r\n＊活動說明<br />\r\n◎報名資格：擁有Lonely Travel部落格的會員。<br />\r\n◎報名方式：請回答問題，留下正確資料就有機會獲得產品並參與此次活動。<br />\r\n<br />\r\n◎活動流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份產品。<br />\r\n2.閱讀並發表體驗心得：錄取者收到產品後，需在14天內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範：<br />\r\n(1)字數300字以上，須包含個人讀後心得。<br />\r\n(2)圖片5張以上，可為：產品完整包裝、產品圖片、體驗情境照、與產品合照                                 ',
            try_notice: '',
            try_count: '30',
            start_at: '2024-09-10 00:00:00',
            end_at: '2024-10-06 23:59:00',
            show_at: '2024-09-10 00:00:00',
            hide_at: '2024-09-22 23:59:00',
            status: '0',
            try_join_count: 162,
            try_join_pass_count: '0',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '30',
            tag_id: '6151',
            online_article_count: '30',
            try_end_url: '',
            memo1: '',
            memo2: '300字',
            memo3: '5張照片',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '1',
            tryget: '最純粹的美味！歐洲進口天然酵母製作，添加美國進口小麥 天然奶油胚芽 Ｘ 天然酵母 Ｘ 美國小麥  小麥含有豐富的維生素和礦物質，是歐美健康飲食的首選！小麥胚芽更是維生素B主要的來源，天然成分負擔小  奶油香氣濃郁、膳食纖維含量高，具有飽足感，簡單又純粹的美味～',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1524396309943-e03f5249f002?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1477089884677-c596568bd120?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
            ],
            videos: [
                {
                    title: '【健司-奶油胚芽餅乾】採用歐洲天然酵母 真材實料的好滋味！',
                    src: 'https://images.unsplash.com/photo-1477089884677-c596568bd120?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: 'https://www.youtube.com/shorts/31orc4RyQuM',
                    embed: {
                        title: '【健司-奶油胚芽餅乾】採用歐洲天然酵母 真材實料的好滋味！',
                        author_name: 'Lonely Travel',
                        author_url: 'https://www.youtube.com/',
                        type: 'video',
                        height: 200,
                        width: 113,
                        version: '1.0',
                        provider_name: 'YouTube',
                        provider_url: 'https://www.youtube.com/',
                        thumbnail_height: 360,
                        thumbnail_width: 480,
                        thumbnail_url:
                            'https://i.ytimg.com/vi/31orc4RyQuM/hq2.jpg',
                        html: '<iframe width="200" height="150" src="https://www.youtube.com/embed/31orc4RyQuM?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen title="【健司-奶油胚芽餅乾】採用歐洲天然酵母 真材實料的好滋味！"></iframe>',
                    },
                    in_title: '1',
                    in_content: '1',
                },
            ],
        },
        {
            id: '14263',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: 'PARITOU',
            area: '',
            name: 'Paritou x KUROMI -混果系列組合-焦糖甜心一盒+玉米濃湯一盒',
            description: '',
            image: 'https://images.unsplash.com/photo-1593994602837-530142086918?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.hhmbuy.com/collections/nut-kuromi?rcode=PI88',
            price: '760',
            note1: '3包/盒，50G/包',
            note2: 'https://docs.google.com/document/d/17AC_ngsMGJlWE711I2oBI5cSUdsJFgtC/edit?usp=sharing&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '焦糖甜心口味-嚴選美國杏仁果及印尼腰果混搭調味，全程嚴格把關，低溫烘焙。保留每顆堅果營養元素，經典焦糖牛奶裹附在飽滿的堅果上，微微焦糖香氣，甜香不膩口。<br />\r\n玉米濃湯口味-嚴選美國杏仁果及印尼腰果混搭翻炒，全程嚴格把關低溫烘焙，保留每顆堅果營養元素，將堅果均勻的裹覆特殊調理的玉米濃湯粉，進行二次烘烤 ，每一口都是玉米濃湯的鹹奶香，小朋友大人都喜歡~<br />\r\n<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】500 字以上，撰文請以口感、滿足幸福感、產品品質及包裝質感為主<br />\r\n【拍攝重點】6張以上照片，清楚拍到產品、品牌',
            try_notice: '',
            try_count: '30',
            start_at: '2024-10-19 06:00:00',
            end_at: '2024-12-07 23:59:00',
            show_at: '2024-09-30 08:00:00',
            hide_at: '2024-10-13 23:59:00',
            status: '-1',
            try_join_count: 134,
            try_join_pass_count: '30',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '30',
            tag_id: '6043',
            online_article_count: '30',
            try_end_url: '',
            memo1: '',
            memo2: '500字以上',
            memo3: '6張以上',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1593994602837-530142086918?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1574699404005-b6120622b1e7?q=80&w=1936&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                },
                {
                    title: '',
                    src: 'https://images.unsplash.com/photo-1574699404005-b6120622b1e7?q=80&w=1936&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                    link: '',
                    in_title: '1',
                    in_content: '0',
                }
            ],
            videos: [],
        },
        {
            id: '14260',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '小食創合',
            area: '',
            name: '【Haloa Poke】 蒜味檸檬醬、韓式泡菜醬',
            description: '',
            image: 'https://images.unsplash.com/photo-1503933063112-76b707f06741?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.innolife.com.tw/collections/mini-sauce',
            price: '120/包',
            note1: '100g/包',
            note2: 'https://docs.google.com/document/d/1qI7DZnopb9yT0URrihI0WoYFlmhx9DQQ/edit?usp=sharing&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '🌴 由夏威夷拌飯品牌Haloa Poke與小食創合聯名開發的特製醬料<br />\r\n★ 便攜設計，隨時隨地享用：100g輕便吸嘴袋包裝，轉開即用，無論野餐或旅行，都能輕鬆攜帶，隨時享用。<br />\r\n<br />\r\n【Haloa Poke】蒜味檸檬醬 100g<br />\r\n🍋 清新口感，百搭風味：檸檬的酸香結合蒜味的獨特調和，增添每道料理的清爽感。<br />\r\n🍋 輕鬆料理，提升美味：只需簡單拌入，即可讓沙拉、肉食、炸物、麵包等料理瞬間升級<br />\r\n🍋 適合夏季，清涼不膩：專為炎熱夏季設計的清爽醬料，讓每一口都感受到涼爽的滋味。<br />\r\n<br />\r\n【Haloa Poke】韓式泡菜醬 100g<br />\r\n★ 辛香開胃，百搭風味：融合泡菜的酸辣和微甜，增添每道料理的活力和層次感。<br />\r\n★ 輕鬆料理，提升美味：只需簡單拌入，即可讓炒飯、麵條、烤肉等料理瞬間充滿韓式風味。<br />\r\n★ 適合各季，酸辣開胃：不論春夏秋冬，這款醬料都能為你的味蕾帶來清爽刺激的感受。<br />\r\n<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】500 字以上，6張以上照片，清楚拍到產品、品牌，撰文請以食用口感、體驗後感受、產品品質及包裝質感為主<br />\r\n【拍攝重點】6張以上照片，清楚拍到產品、品牌',
            try_notice: '',
            try_count: '30',
            start_at: '2024-10-23 06:00:00',
            end_at: '2024-12-07 23:59:00',
            show_at: '2024-09-30 08:00:00',
            hide_at: '2024-10-18 11:59:00',
            status: '-1',
            try_join_count: 89,
            try_join_pass_count: '30',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '25',
            tag_id: '6082',
            online_article_count: '24',
            try_end_url: '',
            memo1: '',
            memo2: '500字以上',
            memo3: '6張以上',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '14254',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '安心良食',
            area: '',
            name: '池上鄉農會 紅豆紫米粥',
            description: '',
            image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.safefood.tw/products/47121207850210',
            price: '100/包',
            note1: '260g/包',
            note2: 'https://docs.google.com/document/d/1wz1dhtm7HugD3FkLtMBi5NwOKl2ObctD/edit?usp=sharing&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '【池上鄉農會-紅豆紫米粥】<br />\r\n是一款傳統與現代結合的美味選擇，嚴選台灣紅豆與紫米，經過精心烹煮，保留了天然食材的原始風味與營養。<br />\r\n紅豆帶來細膩的甜味，紫米則為口感增添了層次感與豐富的營養成分。這款粥既能作為日常甜品，也能在寒冷的季節裡為您送上一份暖心的滋味，是一款適合全家共享的美味良食。<br />\r\n<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】200字以上，撰文請以口感、方便性以及在「安心良食」品牌可【"一站購齊""各種農產品、農會產品"】特點為主。<br />\r\n【拍攝重點】5張以上照片，產品獨照、使用情境、商品特寫近照，如能拍短影片更好。<br />\r\n<br />\r\n',
            try_notice: '',
            try_count: '30',
            start_at: '2024-10-19 06:00:00',
            end_at: '2024-11-02 23:59:00',
            show_at: '2024-09-30 08:00:00',
            hide_at: '2024-10-13 23:59:00',
            status: '-1',
            try_join_count: 132,
            try_join_pass_count: '30',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '29',
            tag_id: '6037',
            online_article_count: '28',
            try_end_url: '',
            memo1: '',
            memo2: '200字以上',
            memo3: '5張以上',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '14257',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '小食創合',
            area: '',
            name: '時光黑金滷肉',
            description: '',
            image: 'https://images.unsplash.com/photo-1509845350455-fb0c36048db1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.innolife.com.tw/products/ready-to-eat-food-braised-pork-120g',
            price: '119/包',
            note1: '120g/包 (2~3人份)',
            note2: 'https://docs.google.com/document/d/120SmVxHCx4f-IhyA0LXh0wVU2yrH7i17/edit?usp=sharing&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '得來速料理【小食創合】時光黑金滷肉 熟悉的家鄉味 滷肉飯 常溫調理包<br />\r\n<br />\r\n★ 正宗中南部「黑金滷肉」風味<br />\r\n★ 完美平衡鹹香與微甜，滷出媽媽的味道<br />\r\n★ 經SGS檢驗合，無添加防腐劑，食用更安心<br />\r\n★ 加熱即食➜單身貴族的懶人包<br />\r\n★ 小巧包裝、常溫保存➜出門在外好方便<br />\r\n★ 輕鬆搞定各種料理➜家庭主婦的神奇寶貝<br />\r\n★ 追劇糧食、電玩迷的精神糧食、加班人的料理包<br />\r\n★ 每包可製成2~3碗滷肉飯，小家庭剛剛好<br />\r\n<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】 500 字以上， 撰文請以食用口感、體驗後感受、產品品質及包裝質感為主<br />\r\n【拍攝重點】6張以上照片，清楚拍到產品、品牌<br />\r\n<br />\r\n',
            try_notice: '',
            try_count: '30',
            start_at: '2024-10-19 06:00:00',
            end_at: '2024-12-07 23:59:00',
            show_at: '2024-09-30 08:00:00',
            hide_at: '2024-10-13 23:59:00',
            status: '-1',
            try_join_count: 120,
            try_join_pass_count: '30',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '30',
            tag_id: '6040',
            online_article_count: '30',
            try_end_url: '',
            memo1: '',
            memo2: '500',
            memo3: '6張以上',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '14242',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '健司',
            area: '',
            name: '匠心鑄就，一鍋入魂：三上食樂-極上牛肉壽喜燒鍋物 | 濃郁牛肉香、四季皆宜的美味！',
            description: '',
            image: 'https://images.unsplash.com/photo-1555881400-edfa57db45be?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: '新品',
            price: '320',
            note1: '',
            note2: 'https://docs.google.com/document/d/1zYR8LWlDnqSIDKXoQpMo25eNI2aPTKME/edit?usp=sharing&ouid=101430024725455801070&rtpof=true&sd=true',
            try_content:
                '【正宗日式口味，傳遞美好祝福】<br />\r\n極上牛肉壽喜燒鍋物採正宗日式壽喜燒湯底，完美呈現出地道的和風滋味。料理不僅是味覺的饗宴，更帶有「好事將至」的寓意。壽喜燒在日本象徵著團圓與吉祥，無論是家人團聚還是好友相伴，在享用美味的同時，為未來的日子增添更多幸福與好運。<br />\r\n<br />\r\n【雙重享受：正宗和風與清爽開鍋】<br />\r\n「極上牛肉壽喜燒鍋物」提供兩種不同的吃法，讓您根據心情口味選擇最適合的方式：<br />\r\n•\t正宗和風吃法：加入250cc的開水及鍋料煮沸，蘸上輕盈的生雞蛋液，立即享用傳統的道地日式風味。滑嫩的口感搭配濃郁的壽喜燒鍋底，讓每一口都充滿層次感，彷彿日本家庭的溫馨味道。<br />\r\n•\t清爽開鍋吃法：加入600cc的開水及鍋料煮沸，對於喜歡清爽口感的人，可以搭配新鮮食材，保留食材的天然鮮美，帶來更為輕盈的味覺體驗。<br />\r\n兩種吃法，滿足不同的味蕾需求，無論是豐富濃郁還是清淡爽口， 都是冬季開鍋首選。<br />\r\n<br />\r\n【年底節慶的最佳選擇】<br />\r\n年底節慶如聖誕、新年，總少不了一鍋象徵團圓與美好祝福的料理。「極上牛肉壽喜燒鍋物」不僅適合在這些場合享用，還能為節日增添濃厚的歡慶氣氛。無論是與家人共享，還是招待朋友，這鍋壽喜燒將讓每一位賓客感受到來年的美好期盼，並在溫馨的氛圍中共度難忘的節慶時光。<br />\r\n選擇「極上牛肉壽喜燒鍋物」，讓正宗日式風味溫暖您的冬季，為節日帶來無盡的幸福與好運！<br />\r\n<br />\r\n哪裡買：全聯<br />\r\n<br />\r\n<br />\r\n＊活動說明<br />\r\n◎報名資格：限Lonely Travel註冊會員。<br />\r\n◎報名方式：點選立即參加按鈕並留下正確資料。<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，Lonely Travel將提供錄取者全聯禮券400元，須自行購買商品（極上牛肉壽喜燒鍋物一盒）。<br />\r\n2.試用並發表體驗心得：錄取者收到產品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約12天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n(1)文章字數500字以上，須包含個人體驗心得。<br />\r\n(2)圖片5張以上，可為：產品完整包裝、Logo、產品圖片、體驗情境照、與產品合照。',
            try_notice: '',
            try_count: '30',
            start_at: '2024-09-26 17:00:00',
            end_at: '2024-11-17 23:59:00',
            show_at: '2024-09-26 09:00:00',
            hide_at: '2024-10-10 00:00:00',
            status: '-1',
            try_join_count: 119,
            try_join_pass_count: '13',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '30',
            tag_id: '6115',
            online_article_count: '30',
            try_end_url: '',
            memo1: '頂級牛肉',
            memo2: '500字',
            memo3: '5張照片',
            memo4: '提供禮券購買',
            label_image_url: '',
            show_trial_exp: '1',
            rate: {
                rate1: {
                    name: '方便料理（10為最高，1為最低）',
                    avg: 9,
                },
                rate2: {
                    name: '好吃入味（10為最高，1為最低）',
                    avg: 9,
                },
                rate3: {
                    name: '冬天必買（10為最高，1為最低）',
                    avg: 8,
                },
                rate4: {
                    name: '包裝美感（10為最高，1為最低）',
                    avg: 8,
                },
                rate5: {
                    name: '總評分',
                    avg: 9,
                },
            },
            tryget: '日本人常用壽喜燒來象徵團圓與吉祥。這次不用飛去日本就可以吃到的道地日式風味！方便調理，加熱加料即可開吃；湯頭濃郁，每一口都充滿層次感；食材入味，每塊料都吸飽湯汁精華。香甜醬香滋味，甜鹹適中，超級下飯，還不趕快去全聯買起來！',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '13981',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '惠珍軒',
            area: '台北市大同區',
            name: '【到店體驗】惠珍軒珍小包系列 任選6包！',
            description: '',
            image: 'https://images.unsplash.com/photo-1487511657539-186f9172833f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://google.com',
            price: '720',
            note1: '門市地址：台北市大同區迪化街1段205號',
            note2: 'https://docs.google.com/document/d/1IyhSP526xoHR99tplhyTOF3a8iH7MePJ/edit?usp=sharing&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '我們是台北迪化街六十年老店<br />\r\n現在以「惠珍軒」開啟新的篇章✨<br />\r\n將提供最新鮮的品質、最實惠的價格、最健康的飲食觀念！<br />\r\n<br />\r\n📌主要販售商品<br />\r\n常溫：新鮮堅果、特色果乾、古早味零嘴、澎湖伯商品<br />\r\n低溫：台南周氏冰鎮滷味、台東玉米放山雞、招牌肉桂捲<br />\r\n<br />\r\n惠珍軒招牌精選#珍小包，眾多熱門品項均一價$120💰 任選6項600元<br />\r\n健康零嘴讓您能隨時放在包包帶著吃😋 陪伴您每一刻❤️<br />\r\n<br />\r\n＊門市地址：台北市大同區迪化街1段205號（門口夥伴為魚刺人雞蛋糕）<br />\r\n建議到店時間：11-17點之間，平日佳（避免假日人潮較多不好拍照體驗）<br />\r\n<br />\r\n◎活動流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者須在特定期間內 11:00-17:00到店兌換商品。<br />\r\n2.到店體驗並發表體驗心得：錄取者需在指定天數到店體驗，最晚需於10/27（日）前到店體驗完畢，<br />\r\n並於體驗完畢後於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n＊兌換時需要出示 “身份證” 以供店家核對身份。<br />\r\n＊請在報名時確保所填寫的姓名正確無誤，以避免兌換時出現問題。<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】500字以上，撰文請以『介紹門市商品販售』為主。<br />\r\n【照片】至少六張照片以上，需清楚拍到門市品牌、店內商品，如能拍短影片更好。',
            try_notice: '',
            try_count: '30',
            start_at: '2024-10-11 12:00:00',
            end_at: '2024-12-07 23:59:00',
            show_at: '2024-09-11 08:00:00',
            hide_at: '2024-10-11 12:00:00',
            status: '-1',
            try_join_count: 71,
            try_join_pass_count: '30',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '32',
            tag_id: '6031',
            online_article_count: '32',
            try_end_url: '',
            memo1: '',
            memo2: '500字以上',
            memo3: '6張以上',
            memo4: '出示身分證',
            label_image_url: '',
            show_trial_exp: '0',
            rate: {
                rate1: {
                    name: '',
                    avg: 1,
                },
                rate2: {
                    name: '',
                    avg: 1,
                },
                rate3: {
                    name: '',
                    avg: 1,
                },
                rate4: {
                    name: '',
                    avg: 1,
                },
                rate5: {
                    name: '',
                    avg: 1,
                },
            },
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '13963',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '艾莉生活有限公司',
            area: '',
            name: '超即溶·凍乾咖啡 -綜合8入',
            description: '',
            image: 'https://images.unsplash.com/photo-1580946443359-1126222f9224?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.just-coffees.com/products/mix8',
            price: '329',
            note1: '綜合8杯/盒，2g/杯',
            note2: 'https://docs.google.com/document/d/1gydV1PVmh9qnVDU7bNy8WhNEXmrnYmuN/edit?usp=sharing&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '你的隨身咖啡師、3秒還原手沖風味！<br />\r\nEasy      ｜  0-100度C  冷熱皆即溶<br />\r\nHealthy｜ 0脂肪、0加糖、0人工添加、0防腐劑<br />\r\nBreezy  ｜ 3秒隨沖即刻享有！<br />\r\n100%阿拉比卡莊園級咖啡豆，採用生醫級凍乾技術鎖住最鮮風味！不須使用咖啡機、也無須漫長等待沖泡時間，適合露營、登山、出差、出國旅遊和忙碌工作的你！隨時為自己沖一杯好咖啡，享自在時光。<br />\r\n<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】500字以上，撰文請以產品品質、包裝質感、不同搭配的風味呈現為主。<br />\r\n【照片】至少六張照片以上，與產品合照、使用情境、商品特寫近照、，如能拍短影片更好。',
            try_notice: '',
            try_count: '30',
            start_at: '2024-10-07 00:00:00',
            end_at: '2024-10-27 23:59:00',
            show_at: '2024-09-07 08:00:00',
            hide_at: '2024-10-04 08:00:00',
            status: '-1',
            try_join_count: 174,
            try_join_pass_count: '28',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '24',
            tag_id: '6034',
            online_article_count: '24',
            try_end_url: '',
            memo1: '歐洲金黃起司',
            memo2: '500字以上',
            memo3: '6張以上',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            rate: {
                rate1: {
                    name: '好吃涮嘴',
                    avg: 1,
                },
                rate2: {
                    name: '起司濃厚',
                    avg: 1,
                },
                rate3: {
                    name: '份量充足',
                    avg: 1,
                },
                rate4: {
                    name: '回購率高',
                    avg: 1,
                },
                rate5: {
                    name: '總評分',
                    avg: 1,
                },
            },
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
        {
            id: '13960',
            category_id: '169',
            category_name: '美食',
            vote: 0,
            type: '美食',
            shop: '祐全生技有限公司',
            area: ' ',
            name: '牛樟芝咖啡',
            description: '',
            image: 'https://images.unsplash.com/photo-1558369605-a9c40729e0b8?q=80&w=2011&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            link: 'https://www.pcstore.com.tw/youcanbiotech/M85719046.htm',
            price: '620',
            note1: '10包/盒',
            note2: 'https://docs.google.com/document/d/142AaLxL-aAVd_I-q70mF1o294U4O6UQ3/edit?usp=sharing&ouid=103956128374093605205&rtpof=true&sd=true',
            try_content:
                '☕️ 牛樟芝和咖啡怎麼搭<br />\r\n牛樟芝本身帶有苦味，特選阿拉比卡咖啡豆<br />\r\n是因為此款豆子富含巧克力、堅果、水果風味<br />\r\n<br />\r\n試想現在你正要吃下一塊80％黑巧克力<br />\r\n巧克力散發出來的香味與濃厚尾韻的苦味<br />\r\n是不是讓你無法自拔<br />\r\n<br />\r\n☕️ 牛樟芝咖啡 就是這樣的概念 同時也要讓你健康的喝、喝的健康<br />\r\n<br />\r\n一日能量與靈感的啟動 不如為自己泡杯咖啡吧<br />\r\n<br />\r\n★特選三萜含量最多、活性最高的5年生牛樟芝<br />\r\n★每100公克牛樟芝子實體含12.5公克三萜類<br />\r\n★每一口咖啡都蘊含豐富的天然牛樟芝精華<br />\r\n★淺中焙阿拉比卡咖啡豆，微苦回甘<br />\r\n★通過行政院90天牛樟芝毒理實驗<br />\r\n<br />\r\n◎體驗流程<br />\r\n1.錄取通知：將透過email通知錄取之會員，錄取者可以獲得一份商品。<br />\r\n2.試用並發表體驗心得：錄取者收到商品後，需在指定天數內於部落格發表一篇體驗文章，並依照信件指示回覆文章連結。（約14天，時間依屆時錄取信件通知為準）<br />\r\n3.體驗文章規範（以屆時提供撰文大綱為準）：<br />\r\n【文章字數】500字以上，撰文請體驗心得分享、口感為主。<br />\r\n【照片】至少六張照片以上，與產品合照、使用情境、商品特寫近照、，如能拍短影片更好。',
            try_notice: '',
            try_count: '30',
            start_at: '2024-10-07 00:00:00',
            end_at: '2024-10-27 23:59:00',
            show_at: '2024-09-09 12:00:00',
            hide_at: '2024-10-04 08:00:00',
            status: '-1',
            try_join_count: 108,
            try_join_pass_count: '30',
            try_questionnaire_id: 0,
            is_questionnaire: false,
            personal_event_id: 0,
            article_count: '26',
            tag_id: '6028',
            online_article_count: '26',
            try_end_url: '',
            memo1: '',
            memo2: '500字以上',
            memo3: '6張以上',
            memo4: '',
            label_image_url: '',
            show_trial_exp: '0',
            rate: {
                rate1: {
                    name: '',
                    avg: 1,
                },
                rate2: {
                    name: '',
                    avg: 1,
                },
                rate3: {
                    name: '',
                    avg: 1,
                },
                rate4: {
                    name: '',
                    avg: 1,
                },
                rate5: {
                    name: '',
                    avg: 1,
                },
            },
            tryget: '',
            sendway: '',
            contentrule: '',
            baseline: '',
            keywords: [''],
            images: [],
            videos: [],
        },
    ];
    const { id } = getQuery(event);
    
    if (id) {
        return DUMMY_DATA.find(product => product.id === id);
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
    return DUMMY_DATA;
});
